export { default as StartScreen } from './StartScreen'
export { default as LoginScreen } from './LoginScreen'
export { default as RegisterScreen } from './RegisterScreen'
export { default as ResetPasswordScreen } from './ResetPasswordScreen'
export { default as Home } from './Home'
export { default as MovieDetail1 } from './movieDetails2'
export { default as VideoPlay } from './VideoPlay'
export {default as MovieDetail} from './Moviedetail'